// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzftDb-yeJKIshBh62niPfYgiFtuC_2IQ',
    appId: '1:1013321541071:web:38cccec904569b2ecbdeba',
    messagingSenderId: '1013321541071',
    projectId: 'bluetup-inc-b59a5',
    authDomain: 'bluetup-inc-b59a5.firebaseapp.com',
    storageBucket: 'bluetup-inc-b59a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXgsownw1Lt1nT2w7TYV-vg4B01ULqXKQ',
    appId: '1:1013321541071:android:e8e37b29bc8381ebcbdeba',
    messagingSenderId: '1013321541071',
    projectId: 'bluetup-inc-b59a5',
    storageBucket: 'bluetup-inc-b59a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3cXoysB-OV5qyJsasL-hxW2oh0AskryU',
    appId: '1:1013321541071:ios:0a21358c515484cfcbdeba',
    messagingSenderId: '1013321541071',
    projectId: 'bluetup-inc-b59a5',
    storageBucket: 'bluetup-inc-b59a5.appspot.com',
    iosClientId:
        '1013321541071-o9ch0fpolv49gfkafgkrkuthu5g7u49k.apps.googleusercontent.com',
    iosBundleId: 'com.bluetup.bluetupInc',
  );
}
